# Generated by Django 3.2.13 on 2022-05-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_librarymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarymodel',
            old_name='title',
            new_name='name',
        ),
    ]
